version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "chiassotv-server:1.0"
    container_name: chiassotv-server
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - data:/mnt/data
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
  db:
    image: "mysql/mysql-server:latest"
    container_name: "chiassotv-mysql"
    ports:
     - "3306:3306"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

volumes:
  data:
    external: false