version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "chiassotv-server:1.0"
    container_name: chiassotv-server
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - data:/mnt/data
    networks:
      appnet:
        ipv4_address: "10.5.0.20"
        aliases:
          - server
    deploy:
      mode: replicated
      replicas: 2
  db:
    image: "mysql"
    container_name: "chiassotv-mysql"
    ports:
      - "3306:3306"
    networks: 
      appnet:
        ipv4_address: "10.5.0.10"
        aliases:
          - database
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: chiassotv
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: chiassotv

volumes:
  data:
    external: true

networks:
  appnet: